# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    adapter: sqlite3
    database: db/development.sqlite3
  cable:
    <<: *default
    adapter: sqlite3
    database: db/cable.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>

  cache:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['POSTGRES_DB'] %>_cache
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>

  cable:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['POSTGRES_DB'] %>_cable
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>

  queue:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['POSTGRES_DB'] %>_queue
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>
